---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appsnaps-appassets.html 
summary: 애플리케이션 스냅샷에 대한 애플리케이션 자산 나열 
---
= 애플리케이션 스냅샷에 대한 애플리케이션 자산 나열
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appSnaps/{appSnap_id}/appAssets`#

컬렉션에서 일치하는 모든 리소스를 JSON 배열로 반환합니다. 요청에 개별 필드가 지정된 경우, items JSON 배열에는 지정된 순서대로 각 일치하는 리소스에 대해 요청된 필드가 포함됩니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| app_id | 문자열 | 경로 | 참  a| 
포함하는 앱 리소스의 ID



| appSnap_id | 문자열 | 경로 | 참  a| 
포함된 appSnap 리소스의 ID



| 포함 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 어떤 필드를 반환해야 하는지 지정합니다.

URL 예: "include=id", "include=id,name"

OpenAPI 예: "id"

* 예: assetType,assetName




| 제한 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 반환할 최대 리소스 수를 나타냅니다.

URL 예: "limit=2"

OpenAPI 예제: "2"

|===


== 응답

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 항목 | array[다음 중 하나: link:#appAsset_1_1_get_response_body["appAsset_1.1_get_response_body"], array[]] | 참  a| 



| 메타데이터 | link:#type_astra_metadata_list["type_astra_메타데이터_목록"] | 참  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAssets",
  "version": "1.1",
  "items": [
    [
      "Pod",
      "mediawiki-69c6fcf864-2wx6l"
    ],
    [
      "ReplicaSet",
      "mediawiki-69c6fcf864"
    ],
    [
      "Service",
      "mediawiki"
    ],
    [
      "Deployment",
      "mediawiki"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Kubernetes 그룹/버전/종류를 포함하는 JSON 객체입니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 그룹 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 그룹 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 종류 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 kind 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 버전 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 버전 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254


|===
[role="api-collapsible-fifth-title"]
type_json

Kubernetes 리소스 정의의 전체 내용을 포함하는 JSON 객체입니다.

[role="api-collapsible-fifth-title"]
라벨

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
레이블 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| 값 | 문자열 | 참  a| 
레이블 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
appAsset_1.1_get_response_body

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-appAsset"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| assetType | 문자열 | 참  a| 
Kubernetes에서 가져온 자산의 유형을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 
Kubernetes 메타데이터가 생성된 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| GVK | link:#GVK["GVK"] | 참  a| 
Kubernetes 그룹/버전/종류를 포함하는 JSON 객체입니다.



| 리소스 | link:#type_json["type_json"] | 거짓  a| 
Kubernetes 리소스 정의의 전체 내용을 포함하는 JSON 객체입니다.



| assetID | 문자열 | 참  a| 
Kubernetes에서 할당한 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 라벨 | 배열[link:#labels["라벨"]] | 참  a| 
자산과 연결된 Kubernetes 레이블을 각각 포함하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| assetName | 문자열 | 참  a| 
Kubernetes에서 할당한 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 네임스페이스 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 네임스페이스를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_목록

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 계속 | 문자열 | 거짓  a| 



| 카운트 | 숫자 | 거짓  a| 



| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====