---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-.html 
summary: 클라우드용 클러스터를 검색합니다 
---
= 클라우드용 클러스터를 검색합니다
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}`#

JSON 응답 본문에 저장된 Cluster API 리소스를 반환합니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| cloud_id | 문자열 | 경로 | 참  a| 
포함된 클라우드 리소스의 ID



| 클러스터_ID | 문자열 | 경로 | 참  a| 
목록에 표시할 클러스터 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored Cluster API resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-cluster"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"
* "1.4"
* "1.5"
* "1.6"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
클러스터 이름을 포함하는 JSON 문자열입니다. 지정하지 않으면 클러스터의 Kubernetes 이름이 사용됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 이 문자열은 XSS, 유니코드, 디렉터리 탐색 및 SQL 인젝션 공격을 방지하기 위해 내부적으로 유효성 검사를 거칩니다.




| 상태 | 문자열 | 참  a| 
클러스터의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pending" - 클러스터가 검색될 예정입니다.
* "discovering" - 클러스터가 검색 중입니다
* "provisioning" - 클러스터가 프로비저닝되는 중입니다
* "running" - 클러스터가 정상적으로 실행 중입니다.
* "failed" - 클러스터가 영구적인 실패 상태에 있습니다.
* "removed" - 현재 클러스터에 접근할 수 없습니다.
* "unknown" - 클러스터 상태를 확인할 수 없습니다




| stateUnready | 배열[string] | 참  a| 
클러스터가 "실행 중" 상태로 전환되지 못하는 이유, "실행 중" 상태에서 문제가 발생하는 이유, 또는 "실패"나 "제거됨" 상태로 전환된 이유를 각각 나타내는 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| managedState | 문자열 | 참  a| 
클러스터의 관리 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pending" - 클러스터가 검색되거나 추가될 예정입니다.
* "ineligible" - 클러스터가 "running" 상태이며 관리 대상이 아니고 관리 대상 자격도 없습니다. 이 부적격 사유는 unready 키 값에 제공됩니다.
* "unmanaged" - 클러스터가 "running" 또는 "failed" 상태이며, 관리 대상이 아니며, 관리 대상이 될 수 있는 상태입니다
* "managing" - 클러스터가 "running" 상태이며 관리 프로세스가 진행 중입니다.
* "managed" - 클러스터가 "running", "failed" 또는 "removed" 상태이며 관리되고 있습니다.




| protectionState | 문자열 | 참  a| 
클러스터의 보호 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "full" - 클러스터의 기본 스토리지 클래스는 스냅샷을 지원합니다.
* "partial" - 클러스터에는 스냅샷을 지원하지 않는 storageClasses만 있습니다
* "atRisk" - 클러스터의 기본 스토리지 클래스는 스냅샷을 지원하지 않습니다




| protectionStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
현재 보호 상태에 대한 추가 정보(현재 상태에 도달한 이유 포함)를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0




| restoreTargetSupported | 문자열 | 거짓  a| 
클러스터가 애플리케이션 데이터 관리 작업의 _target_이 될 수 있는지 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 클러스터는 앱 데이터 관리 작업의 적합한 대상입니다.
* "false" - 클러스터는 앱 데이터 관리 작업의 적합한 대상이 _아닙니다_.




| snapshotSupported | 문자열 | 거짓  a| 
클러스터가 애플리케이션 데이터 관리 백업과 같은 작업을 수행할 수 있는지 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 클러스터가 앱 데이터 관리 작업을 수행할 자격이 있습니다.
* "false" - 클러스터는 앱 데이터 관리 작업을 수행할 자격이 _없습니다_.




| managedStateUnready | 배열[string] | 참  a| 
클러스터를 관리할 수 없는 이유 또는 클러스터가 관리되고 있지만 클러스터 관리 중 치명적이지 않은 오류가 발생했음을 나타내는 각 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| managedTimestamp | 문자열 | 거짓  a| 
클러스터가 관리 상태로 전환된 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다. 이 키는 클러스터의 managedState가 "managed"일 때만 반환됩니다.




| tridentVersion | 문자열 | 거짓  a| 
클러스터에 설치된 Trident 버전을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 소프트웨어 버전 스키마를 준수합니다




| acpVersion | 문자열 | 거짓  a| 
클러스터에 설치된 Astra Control Provisioner 버전을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 소프트웨어 버전 스키마를 준수합니다




| tridentManagedState | 문자열 | 거짓  a| 
이 클러스터에서 Trident의 관리 상태를 나타내는 열거형 값 중 하나를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "managed" - 클러스터의 Trident 인스턴스는 Astra에서 관리됩니다
* "unmanaged" - 클러스터의 Trident 인스턴스가 Astra에서 관리되지 않습니다




| tridentManagedStateDesired | 문자열 | 거짓  a| 
Trident의 원하는 관리 상태를 나타내는 값이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "managed" - 이 클러스터에서 Trident를 관리합니다
* "unmanaged" - 이 클러스터에서 Trident를 관리하지 마십시오




| tridentManagedStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 거짓  a| 
상태가 "managed" 또는 "unmanaged"로 전환된 이유에 대한 추가 세부 정보를 나열하는 JSON 객체의 JSON 배열입니다. + 사용 가능한 세부 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| tridentManagedStateAllowed | 배열[string] | 거짓  a| 
특정 tridentManagedState에서 요청할 수 있는 상태입니다. 정의된 각 상태에서 다음과 같은 상태를 요청할 수 있습니다.

* "managed": "managed"
* "unmanaged": "unmanaged"




| inUse | 문자열 | 참  a| 
클러스터에 관리형 애플리케이션이 있는지 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 관리형 애플리케이션이 있는 경우 삭제할 수 없습니다. 정의된 값은 다음과 같습니다.

* "false" - 클러스터 노드가 관리되지 않거나 관리되지만 연결된 관리형 애플리케이션이 없습니다
* "true" - 클러스터가 관리되며 관리되는 애플리케이션이 연결되어 있습니다




| accHost | 문자열 | 거짓  a| 
현재 액세스 중인 Astra Control Center 인스턴스를 이 클러스터에서 호스팅한다는 것을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 이 클러스터는 현재 접속 중인 Astra Control Center 인스턴스를 호스팅하고 있습니다.




| clusterType | 문자열 | 참  a| 
클러스터 유형을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "gke" - Google Kubernetes Engine에서 호스팅되는 Kubernetes
* "aks" - Microsoft Azure Kubernetes Service에서 호스팅되는 Kubernetes
* "eks" - Amazon Elastic Kubernetes Service에서 호스팅되는 Kubernetes
* "rke" - 클러스터는 Rancher 유형입니다
* "tanzu" - 클러스터는 Tanzu Kubernetes Grid 유형입니다
* "openshift" - 클러스터 유형은 OpenShift
* "anthos" - 클러스터는 GKE Anthos 유형입니다
* "kubernetes" - 클러스터는 일반 Kubernetes입니다




| clusterVersion | 문자열 | 거짓  a| 
클러스터 환경의 시맨틱 버전 표현을 나타내는 값을 포함하는 JSON 문자열입니다. Kubernetes 클러스터의 경우 Kubernetes 버전입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 31




| clusterVersionString | 문자열 | 거짓  a| 
클러스터 환경에 대한 확장 버전 정보를 나타내는 값을 포함하는 JSON 문자열입니다. Kubernetes 클러스터의 경우 전체 Kubernetes 버전입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 31




| clusterCreationTimestamp | 문자열 | 거짓  a| 
클러스터가 처음 생성된 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| 네임스페이스 | 배열[string] | 거짓  a| 
클러스터 내의 네임스페이스를 나타내는 JSON 문자열들의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 253




| defaultStorageClass | 문자열 | 거짓  a| 
Kubernetes에 설정된 기본 스토리지 클래스에 해당하는 스토리지 클래스 ID가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| cloudID | 문자열 | 참  a| 
클러스터가 실행 중인 클라우드의 ID를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| credentialID | 문자열 | 거짓  a| 
클러스터의 kubeconfig 파일이 포함된 자격 증명의 ID를 나타내는 값을 담고 있는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다. privateRouteID와 최소한 릴레이 옵션이 포함된 connectorCapabilities가 제공되는 경우 credentialID는 선택 사항입니다. 이러한 항목이 제공되지 않으면 credentialID는 필수이며, 그렇지 않으면 오류가 발생합니다. credentialID와 릴레이 기능을 지원하는 커넥터가 모두 제공되는 경우에도 오류가 발생합니다.




| 위치 | 문자열 | 거짓  a| 
클러스터가 실행되는 클라우드에서 제공하는 값을 포함하는 JSON 문자열로, 클러스터의 클라우드별 위치를 나타냅니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| isMultizonal | 문자열 | 거짓  a| 
클러스터가 실행되는 클라우드에서 제공하는 값을 포함하는 JSON 문자열로, 클러스터가 둘 이상의 가용 영역에 걸쳐 있는지 여부를 나타냅니다. 정의된 값은 다음과 같습니다.

* "true" - 클러스터가 둘 이상의 가용 영역에 걸쳐 있습니다.
* "false" - 클러스터는 단일 가용 영역 내에 완전히 위치해 있습니다.




| privateRouteID | 문자열 | 거짓  a| 
프라이빗 클러스터의 위치 ID가 포함된 JSON 문자열입니다.

* 최소 길이: 1
* 최대 길이: 255




| connectorCapabilities | 배열[string] | 거짓  a| 
이 클러스터와 연결된 커넥터의 기능입니다. 하위 호환성을 위해 선택 사항입니다. 이 항목이 없으면 프록시 기능이 기본적으로 사용됩니다.



| apiServiceID | 문자열 | 거짓  a| 
Kubernetes(k8s) API 서비스 객체의 UUID를 포함하는 JSON 문자열입니다. 클러스터를 고유하게 식별하는 데 사용됩니다.



| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cluster",
  "version": "1.6",
  "id": "b8c3bce9-5f8f-5f5a-a456-2b2eb6cfd2b6",
  "name": "GKE-22",
  "state": "running",
  "stateUnready": [],
  "managedState": "unmanaged",
  "managedStateUnready": [],
  "protectionState": "full",
  "protectionStateDetails": [],
  "tridentVersion": "23.10.0",
  "acpVersion": "23.10.0",
  "tridentManagedState": "managed",
  "tridentManagedStateDetails": [],
  "inUse": "false",
  "clusterType": "kubernetes",
  "clusterVersion": "1.91.1",
  "clusterVersionString": "1.19.1",
  "clusterCreationTimestamp": "2020-08-06T12:24:52.256624Z",
  "namespaces": [
    "kube-system",
    "kube-public",
    "my-app-1"
  ],
  "defaultStorageClass": "31c95aba-99d9-4987-b1bb-000dfce5952c",
  "cloudID": "548bdc1f-f00e-4a23-a062-83265d224d46",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31",
  "location": "europe-west4",
  "isMultizonal": "false",
  "apiServiceID": "6bf33af2-872a-4553-a891-26b510c3edbe",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 응답

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/65",
  "title": "Cluster GET not performed",
  "detail": "The cluster GET call didn't perform the lookup operation on the cluster.",
  "status": "500"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====