---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-settings-.html 
summary: 설정 검색 
---
= 설정 검색
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings/{setting_id}`#

JSON 응답 본문에 저장된 Setting API 리소스를 반환합니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| setting_id | 문자열 | 경로 | 참  a| 
나열할 설정 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored Setting API resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-setting"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
계층적 점 표기법(.)으로 표현된 설정 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 이 문자열은 XSS, 유니코드, 디렉터리 탐색 및 SQL 인젝션 공격을 방지하기 위해 내부적으로 유효성 검사를 거칩니다. 이 값은 런타임에 로드되는 configmap에 지정되며 사용자가 업데이트할 수 없습니다.




| currentConfig | link:#type_json["type_json"] | 참  a| 
이 설정에 대한 현재 구성을 구성하는 키와 값을 포함하는 JSON 객체입니다. 이 객체의 내용은 configSchema 필드에 포함된 JSON 스키마를 준수해야 합니다. 기본값은 configmap에서 제공됩니다. 사용자가 기본값을 변경한 후에는 덮어쓰여지지 않습니다.



| desiredConfig | link:#type_json["type_json"] | 거짓  a| 
이 설정에 대해 요청된 구성을 구성하는 키와 값을 포함하는 JSON 객체입니다. 이 객체의 내용은 configSchema 필드에 포함된 JSON 스키마를 준수해야 합니다. 이 객체는 지정되기 전까지는 존재하지 않습니다. 지정되면 기능 서비스는 해당 서비스에 원하는 구성을 적용할 수 있도록 요청하는 알림을 보냅니다. 그러면 해당 서비스는 유효성 검사를 수행하고 원하는 구성을 현재 구성에 적용할 수 있습니다.



| configSchema | link:#type_json_schema["type_json_schema"] | 참  a| 
이 리소스의 config 속성에 대한 JSON 스키마를 포함하는 JSON 객체입니다. JSON Schema Draft 7을 준수해야 합니다. 리소스에 config 값이 있는 경우 표시된 configSchema에 대한 유효성 검사가 필수입니다. 일반적인 규칙으로, 적절한 경우 구성에 "isEnabled" 필드를 포함하는 것이 좋습니다. "isEnabled" 필드에는 설정이 켜져 있는지("true") 또는 꺼져 있는지("false")를 나타내는 값이 포함됩니다.



| 상태 | 문자열 | 참  a| 
애플리케이션의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "valid" - 현재 구성이 원하는 구성과 일치합니다.
* "pending" - 원하는 구성이 적용되고 있습니다.
* "error" - 원하는 구성을 적용할 수 없습니다.




| stateUnready | 배열[string] | 참  a| 
설정이 성공적으로 적용되지 않은 이유를 나타내는 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp 및 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-setting",
  "version": "1.1",
  "id": "ea510866-47d3-5130-8468-563df4cd6a28",
  "name": "astra.account.smtp",
  "currentConfig": {
    "credential": "",
    "isEnabled": "false",
    "port": 587,
    "relayServer": "smtp.sendgrid.net"
  },
  "configSchema": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "astra.account.smtp",
    "type": "object",
    "properties": {
      "credential": {
        "type": "string",
        "description": "The credential ID for SMTP authentication."
      },
      "isEnabled": {
        "type": "string",
        "description": "This property determines if this setting is enabled or not."
      },
      "port": {
        "type": "integer",
        "description": "The SMTP port. For an unencrypted or a TLS connection, use port 25, 2525, or 587."
      },
      "relayServer": {
        "type": "string",
        "description": "This setting is sometimes referred to as the external SMTP server or the SMTP relay."
      }
    },
    "additionalProperties": false,
    "required": [
      "relayServer",
      "port",
      "isEnabled"
    ]
  },
  "state": "valid",
  "stateUnready": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 응답

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_json

이 설정에 대한 현재 구성을 구성하는 키와 값을 포함하는 JSON 객체입니다. 이 객체의 내용은 configSchema 필드에 포함된 JSON 스키마를 준수해야 합니다. 기본값은 configmap에서 제공됩니다. 사용자가 기본값을 변경한 후에는 덮어쓰여지지 않습니다.

[role="api-collapsible-fifth-title"]
type_json

이 설정에 대해 요청된 구성을 구성하는 키와 값을 포함하는 JSON 객체입니다. 이 객체의 내용은 configSchema 필드에 포함된 JSON 스키마를 준수해야 합니다. 이 객체는 지정되기 전까지는 존재하지 않습니다. 지정되면 기능 서비스는 해당 서비스에 원하는 구성을 적용할 수 있도록 요청하는 알림을 보냅니다. 그러면 해당 서비스는 유효성 검사를 수행하고 원하는 구성을 현재 구성에 적용할 수 있습니다.

[role="api-collapsible-fifth-title"]
속성

[role="api-collapsible-fifth-title"]
type_json_schema

이 리소스의 config 속성에 대한 JSON 스키마를 포함하는 JSON 객체입니다. JSON Schema Draft 7을 준수해야 합니다. 리소스에 config 값이 있는 경우 표시된 configSchema에 대한 유효성 검사가 필수입니다. 일반적인 규칙으로, 적절한 경우 구성에 "isEnabled" 필드를 포함하는 것이 좋습니다. "isEnabled" 필드에는 설정이 켜져 있는지("true") 또는 꺼져 있는지("false")를 나타내는 값이 포함됩니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| $schema | 문자열 | 참  a| 



| 유형 | 문자열 | 참  a| 



| 속성 | link:#properties["속성"] | 참  a| 



| additionalProperties | boolean | 참  a| 



| 필수 | 배열[string] | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp 및 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====