---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-asups-.html 
summary: ASUP 리소스를 검색합니다 
---
= ASUP 리소스를 검색합니다
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/asups/{asup_id}`#

저장된 ASUP API 리소스를 JSON 응답 본문에 반환합니다. AutoSupport 번들의 "creationState"가 "completed" 또는 "partial"인 경우, Accept 헤더에 "_/_" 또는 "application/gzip"을 지정하여 AutoSupport 번들을 다운로드할 수 있습니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| asup_id | 문자열 | 경로 | 참  a| 
나열할 asup 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored ASUP API resource in the JSON response body. If the AutoSupport bundle "creationState" is "completed" or "partial", the AutoSupport bundle can be downloaded by specifying an Accept header containing "*/*" or "application/gzip".
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-asup"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| creationState | 문자열 | 참  a| 
AutoSupport 번들의 생성 상태를 나타내는 값을 포함하는 JSON 문자열입니다. "completed" 및 "partial" 상태의 경우, Accept 헤더에 "_/_" 또는 "application/gzip"이 포함된 리소스 URI에 대한 GET 요청을 수행하여 번들을 다운로드할 수 있습니다. 정의된 값은 다음과 같습니다.

* "실행 중" - AutoSupport 번들 생성이 정상적으로 실행되고 있습니다.
* "완료됨" - AutoSupport 번들 생성이 완료되었습니다.
* "partial" - AutoSupport 번들 생성이 완료되었지만 일부 데이터가 번들에 포함되지 않았습니다.
* "failed" - AutoSupport 번들 생성이 영구적인 실패 상태입니다.




| creationStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
"creationState"가 "partial" 또는 "failed"로 전환된 이유에 대한 추가 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| 업로드 | 문자열 | 참  a| 
AutoSupport 번들 생성 성공 후 업로드 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - AutoSupport 번들을 업로드합니다.
* "false" - AutoSupport 번들을 업로드하지 마십시오.




| uploadState | 문자열 | 거짓  a| 
요청된 경우 AutoSupport 번들 업로드 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pending" - AutoSupport 번들 업로드는 AutoSupport 번들 생성이 완료될 때("creationState"가 "running") 예약됩니다.
* "blocked" - AutoSupport 번들 업로드가 시도되지 않았습니다. 번들이 생성되지 않았거나("creationState"가 "failed") 라이선스가 없어서 업로드가 차단되었습니다.
* "running" - AutoSupport 번들 업로드가 정상적으로 실행 중입니다("creationState"가 "completed" 또는 "partial"인 경우).
* "완료됨" - AutoSupport 번들 업로드가 완료되었습니다.
* "failed" - AutoSupport 번들 업로드가 영구적인 실패 상태입니다.




| uploadStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 거짓  a| 
"uploadState"가 "failed"로 전환된 이유에 대한 추가 세부 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| triggerType | 문자열 | 참  a| 
ASUP 리소스 생성을 촉발한 요인을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "manual" - ASUP 리소스 및 관련 AutoSupport 번들은 수동으로 생성되었습니다.
* "scheduled" - ASUP 리소스와 관련 AutoSupport 번들은 구성된 일정에 따라 생성되었습니다.




| dataWindowStart | 문자열 | 참  a| 
AutoSupport 번들 데이터 수집 기간의 시작 시간을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 기본값은 "dataWindowEnd" 키 값보다 24시간 전입니다. 반드시 "dataWindowEnd" 키 값 이전에 발생해야 합니다. 최대값은 요청 시점으로부터 7일 전입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| dataWindowEnd | 문자열 | 참  a| 
AutoSupport 번들 데이터 수집 기간의 종료 시간을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 기본값은 요청 시의 현재 시간입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-asup",
  "version": "1.0",
  "id": "9950003f-a1c7-5ca7-8930-06eec25f60aa",
  "creationState": "completed",
  "creationStateDetails": [],
  "upload": "false",
  "triggerType": "manual",
  "dataWindowStart": "2020-08-05T12:24:00.000000Z",
  "dataWindowEnd": "2020-08-06T12:24:52.000000Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====