---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-volumes-.html 
summary: 앱의 볼륨을 검색합니다 
---
= 앱의 볼륨을 검색합니다
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/volumes/{volume_id}`#

JSON 응답 본문에 저장된 Volume API 리소스를 반환합니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| app_id | 문자열 | 경로 | 참  a| 
포함하는 앱 리소스의 ID



| volume_id | 문자열 | 경로 | 참  a| 
목록에 표시할 볼륨 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored Volume API resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-volume"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
볼륨 이름이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| 상태 | 문자열 | 거짓  a| 
볼륨의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다.



| 크기 | 문자열 | 거짓  a| 
볼륨의 크기를 포함하는 JSON 문자열입니다.



| 사용된 | 숫자 | 거짓  a| 
프로비저닝된 볼륨에서 사용된 할당량의 바이트 수를 포함하는 JSON 번호입니다.



| usedPercentage | 숫자 | 거짓  a| 
사용된 볼륨의 백분율을 포함하는 JSON 숫자입니다.



| 총 | 숫자 | 거짓  a| 
프로비저닝된 볼륨의 총 바이트 수를 포함하는 JSON 숫자입니다.



| creationToken | 문자열 | 거짓  a| 
볼륨의 생성 토큰이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| snapshotPossible | 문자열 | 거짓  a| 
드라이버가 볼륨의 스냅샷을 수행할 수 있는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 드라이버가 볼륨의 스냅샷을 생성할 수 있습니다
* "false" - 드라이버가 볼륨의 스냅샷을 생성할 수 없습니다




| storageClass | 문자열 | 거짓  a| 
볼륨의 스토리지 클래스를 포함하는 JSON 문자열입니다.

* 정의된 값은 다음과 같습니다.
* 최소 길이: 1
* 최대 길이: 255




| pvcName | 문자열 | 거짓  a| 
볼륨의 PersistentVolumeClaim(PVC) 이름을 포함하는 JSON 문자열입니다.

* 정의된 값은 다음과 같습니다.
* 최소 길이: 1
* 최대 길이: 255




| internalName | 문자열 | 거짓  a| 
대상 스토리지 클러스터의 볼륨 내부 이름을 포함하는 JSON 문자열입니다(사용 가능한 경우). 이 이름은 Kubernetes CSI 드라이버에서 가져옵니다.

* 정의된 값은 다음과 같습니다.
* 최소 길이: 1
* 최대 길이: 255




| appsUsing | 배열[string] | 참  a| 
볼륨을 사용 중인 애플리케이션의 ID를 각각 포함하는 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| storageBackendID | 문자열 | 거짓  a| 
볼륨을 제공하는 스토리지 백엔드의 ID가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 오케스트레이터 | 문자열 | 거짓  a| 
이 볼륨의 오케스트레이터를 포함하는 JSON 문자열입니다. 이 값은 Astra Data Store 볼륨에 대해 정의됩니다. 정의된 값은 다음과 같습니다.

* "trident" - Trident이 이 볼륨을 프로비저닝했습니다.
* "vasa" - NetApp VASA Provider가 이 볼륨을 프로비저닝했습니다.
* "other" - 볼륨이 수동으로 프로비저닝되었거나 오케스트레이터를 알 수 없습니다




| serviceLevel | 문자열 | 거짓  a| 
스토리지 백엔드 수준에서 이 볼륨에 대해 정의된 서비스 품질(QoS) 정책을 포함하는 JSON 문자열입니다. 이 값은 Astra Data Store 볼륨에 대해 정의됩니다.



| exportPolicy | 문자열 | 거짓  a| 
이 볼륨과 연결된 내보내기 정책이 포함된 JSON 문자열입니다. 이 값은 Astra Data Store 볼륨에 대해 정의됩니다.



| nodeId | 문자열 | 거짓  a| 
볼륨을 제공하는 노드 ID가 포함된 JSON 문자열입니다. 이 값은 Astra Data Store 볼륨에 대해 정의됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| healthState | 문자열 | 거짓  a| 
볼륨의 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 이 값은 Astra Data Store 볼륨에 대해 정의됩니다. 정의된 값은 다음과 같습니다.

* "indeterminate" - 리소스의 상태를 확인할 수 없습니다(예: 연결 부족으로 인해)
* "normal" - 해당 리소스에는 알려진 문제가 없으며 인터페이스 사양에 따라 서비스를 제공할 수 있습니다.
* "warning" - 해당 리소스에는 인터페이스 사양에 따라 서비스를 제공하는 데 지장을 주지 않는 알려진 문제가 있습니다.
* "critical" - 해당 리소스에는 인터페이스 사양에 따라 서비스를 제공하는 것을 방해하는 알려진 문제가 있습니다.




| healthStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
현재 상태에 대한 추가 세부 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-volume",
  "version": "1.2",
  "id": "ab5c9fb8-ddba-526f-8bd3-8d5b72cf4f7f",
  "name": "myVolume",
  "state": "ready",
  "size": "512 GiB",
  "used": 10000000000,
  "usedPercentage": 10,
  "total": 10000000000,
  "creationToken": "ba7d4e0c-6ae3-4b6e-859d-9463e7ca4b4e",
  "snapshotPossible": "true",
  "storageClass": "gold",
  "pvcName": "myVolume",
  "internalName": "trident_sd234234_23424_897d_876sd65w",
  "appsUsing": [],
  "orchestrator": "trident",
  "serviceLevel": "gold",
  "exportPolicy": "astra-vp-default",
  "nodeId": "94d16dd2-9beb-4edb-ab58-1a00e9a90052",
  "healthState": "normal",
  "healthStateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====