---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-storageclasses.html 
summary: 클라우드의 스토리지 클래스를 나열합니다 
---
= 클라우드의 스토리지 클래스를 나열합니다
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}/storageClasses`#

컬렉션에서 일치하는 모든 리소스를 JSON 배열로 반환합니다. 요청에 개별 필드가 지정된 경우, items JSON 배열에는 지정된 순서대로 각 일치하는 리소스에 대해 요청된 필드가 포함됩니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| cloud_id | 문자열 | 경로 | 참  a| 
포함된 클라우드 리소스의 ID



| 클러스터_ID | 문자열 | 경로 | 참  a| 
포함된 클러스터 리소스의 ID



| 포함 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 어떤 필드를 반환해야 하는지 지정합니다.

URL 예: "include=id", "include=id,name"

OpenAPI 예: "id"

* 예: id,name




| 제한 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 반환할 최대 리소스 수를 나타냅니다.

URL 예: "limit=2"

OpenAPI 예제: "2"

|===


== 응답

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 항목 | array[다음 중 하나: link:#storageClass_1_1_get_response_body["storageClass_1.1_get_response_body"], array[]] | 참  a| 



| 메타데이터 | link:#type_astra_metadata_list["type_astra_메타데이터_목록"] | 참  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageClasses",
  "version": "1.1",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "my-storage-class"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "standard"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
storageClass_1.1_get_response_body

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-storageClass"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
스토리지 클래스의 이름을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| 프로비저너 | 문자열 | 참  a| 
스토리지 클래스와 연결된 프로비저너를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| 사용 가능 | 문자열 | 참  a| 
관리 상태에서 스토리지 클래스가 클러스터에서 사용 가능한지 또는 클러스터에 추가할 수 있는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "available" - 스토리지 클래스를 사용할 수 있습니다
* "eligible" - 스토리지 클래스는 관리 중일 때 클러스터에서 사용할 수 있습니다.
* "ineligible" - 스토리지 클래스가 관리 중일 때 클러스터에서 사용할 수 없습니다




| allowVolumeExpansion | 문자열 | 참  a| 
스토리지 클래스에서 볼륨 확장이 허용되는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 스토리지 클래스는 볼륨 확장을 허용합니다.
* "false" - 스토리지 클래스는 볼륨 확장을 허용하지 않습니다
* "unavailable" - 스토리지 클래스에서 볼륨 확장이 가능한지 여부를 알 수 없습니다




| reclaimPolicy | 문자열 | 참  a| 
스토리지 클래스의 보존 정책을 나타내는 클라우드별 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| volumeBindingMode | 문자열 | 참  a| 
스토리지 클래스의 바인딩 모드를 나타내는 클라우드별 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| isDefault | 문자열 | 거짓  a| 
스토리지 클래스에 기본 어노테이션이 포함되어 있는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 스토리지 클래스에 기본 주석이 포함되어 있습니다.




| maxSnapshotCount | 숫자 | 거짓  a| 
지원되는 스냅샷 수를 나타내는 JSON 숫자입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 연결됩니다.



| maxBackupCount | 숫자 | 거짓  a| 
지원되는 백업 수를 나타내는 JSON 숫자입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 연결됩니다.



| 가격 | 문자열 | 거짓  a| 
스토리지 클래스의 시간 단위당 통화 단위를 나타내는 JSON 문자열입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 연결됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| 통화 | 문자열 | 거짓  a| 
가격이 측정된 통화의 ISO 4217 3자리 코드를 나타내는 JSON 문자열입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 첨부됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 255




| 성능 | 숫자 | 거짓  a| 
MBps 단위의 성능 서비스 수준 목표(SLO)를 나타내는 JSON 숫자입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 연결됩니다.



| 복원력 | 문자열 | 거짓  a| 
스토리지의 복원력 구성을 나타내는 JSON 문자열입니다. 이 정보는 NetApp에서 제공하는 스토리지 클래스에 연결됩니다. 정의된 값은 다음과 같습니다.

* "regional" - 특정 지역을 사용할 수 없게 되면 볼륨을 사용할 수 없게 됩니다
* "multisite" - 특정 지역을 사용할 수 없게 되더라도 볼륨은 계속 사용 가능합니다.




| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_목록

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 계속 | 문자열 | 거짓  a| 



| 카운트 | 숫자 | 거짓  a| 



| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====