---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-packages.html 
summary: 모든 패키지 나열 
---
= 모든 패키지 나열
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/packages`#

컬렉션에서 일치하는 모든 리소스를 JSON 배열로 반환합니다. 요청에 개별 필드가 지정된 경우, items JSON 배열에는 지정된 순서대로 각 일치하는 리소스에 대해 요청된 필드가 포함됩니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| 필터 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 리소스를 반환하기 위해 어떤 필드를 일치시켜야 하는지를 나타냅니다.

지원되는 연산자는 다음과 같습니다.

* eq - 같음
* lt/gt - 미만/초과
* lte/gte - 이하/이상


URL 예: "filter=field%20eq%20%27value%27"

OpenAPI 예: "field eq 'value'"



| 주문 | 문자열 | 쿼리 | 거짓  a| 
컬렉션을 나열할 때 리소스의 정렬 순서를 나타냅니다.

URL 예시: "orderBy=name", "orderBy=name%20desc"

OpenAPI 예: "name desc"



| 포함 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 어떤 필드를 반환해야 하는지 지정합니다.

URL 예: "include=id", "include=id,name"

OpenAPI 예: "id"

* 예: id,packageName,packageVersion,softwareType




| 제한 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 반환할 최대 리소스 수를 나타냅니다.

URL 예: "limit=2"

OpenAPI 예제: "2"

|===


== 응답

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 항목 | array[다음 중 하나: link:#package_1_0_get_response_body["package_1.0_get_response_body"], array[]] | 참  a| 



| 메타데이터 | link:#type_astra_metadata_list["type_astra_메타데이터_목록"] | 참  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-packages",
  "version": "1.0",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "acc",
      "22.01.0",
      "install"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "acc",
      "22.01.1",
      "patch"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 에서 | 문자열 | 참  a| 



| ~ | 배열[string] | 참  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
dependsOnImages

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| imagePath | 문자열 | 참  a| 
이 Docker 이미지의 경로를 포함하는 JSON 문자열입니다. 레지스트리 이름은 포함해서는 안 되며, 루트에서 이미지까지의 절대 경로만 포함해야 합니다. 예: /globalcicd/acc 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 1023




| imageName | 문자열 | 참  a| 
Docker 이미지 이름이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| imageTag | 문자열 | 참  a| 
이 이미지의 태그/버전을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 31


|===
[role="api-collapsible-fifth-title"]
이미지

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| imageName | 문자열 | 참  a| 
Docker 이미지 이름이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| imagePath | 문자열 | 참  a| 
이 Docker 이미지의 경로를 포함하는 JSON 문자열입니다. 레지스트리 이름은 포함해서는 안 되며, 루트에서 이미지까지의 절대 경로만 포함해야 합니다. 예: /globalcicd/acc 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 1023




| imageTag | 문자열 | 참  a| 
이 이미지의 태그/버전을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 31




| imageDigest | 문자열 | 참  a| 
이 이미지의 다이제스트를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규 표현식은 다음과 같습니다: "^(sha256:)[0-9a-f]{64}$"




| dependsOnImages | 배열[link:#dependsOnImages["dependsOnImages"]] | 거짓  a| 
현재 이미지를 설치하거나 업그레이드하는 데 필요한 이미지를 설명하는 JSON 객체의 JSON 배열입니다.

|===
[role="api-collapsible-fifth-title"]
dependsOnComponents

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| componentName | 문자열 | 참  a| 
컴포넌트의 이름을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| 버전 | 배열[string] | 참  a| 
현재 이미지를 설치하는 데 필요한 구성 요소 버전을 정의하는 JSON 문자열의 JSON 배열입니다.

|===
[role="api-collapsible-fifth-title"]
아티팩트

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| artifactName | 문자열 | 참  a| 
파일 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| artifactIdentifier | 문자열 | 참  a| 
이 파일의 식별자를 포함하는 JSON 문자열입니다. 동일한 패키지 유형의 버전 간에 파일 이름은 변경될 수 있지만 식별자는 일반적으로 동일하게 유지됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 511




| artifactPath | 문자열 | 참  a| 
알려진 Astra Control Center 데이터 저장소/위치의 루트에서 이 아티팩트까지의 경로를 포함하는 JSON 문자열입니다. 예: /vmware/1.0/ 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 1023




| artifactVersion | 문자열 | 거짓  a| 
제공된 경우 해당 아티팩트의 버전을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.
* 최소 길이: 1
* 최대 길이: 31




| dependsOnComponents | 배열[link:#dependsOnComponents["dependsOnComponents"]] | 거짓  a| 
현재 이미지를 설치/업그레이드하는 데 필요한 설치된 구성 요소를 설명하는 JSON 객체의 JSON 배열입니다.

|===
[role="api-collapsible-fifth-title"]
파일

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| fileName | 문자열 | 참  a| 
파일 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| fileIdentifier | 문자열 | 참  a| 
이 파일의 식별자를 포함하는 JSON 문자열입니다. 동일한 패키지 유형의 버전 간에 파일 이름은 변경될 수 있지만 식별자는 일반적으로 동일하게 유지됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 511




| fileMediaType | 문자열 | 참  a| 
파일 미디어 유형을 포함하는 JSON 문자열입니다.  https://www.iana.org/assignments/media-types/media-types.xhtml["IANA"]에 정의된 모든 미디어 유형이 정의된 값입니다. 또한 YAML 파일의 경우 application/x-yaml 또는 application/x-yaml도 지원됩니다.

* 최소 길이: 1
* 최대 길이: 211




| fileContents | 문자열 | 참  a| 
파일 내용을 담고 있는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Base64 스키마를 준수합니다. FIXME - 압축 방식을 어떻게 지정해야 할까요? 어떤 알고리즘 등을 사용해야 할까요?


|===
[role="api-collapsible-fifth-title"]
upgradableVersions

패키지 버전으로 업그레이드할 수 있는 최소 및 최대 버전을 포함하는 JSON 객체입니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| minVersion | 문자열 | 거짓  a| 
패키지 버전으로 업그레이드할 수 있는 최소 버전을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.




| maxVersion | 문자열 | 거짓  a| 
패키지 버전으로 업그레이드할 수 있는 최대 버전을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.


|===
[role="api-collapsible-fifth-title"]
종속성

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| componentName | 문자열 | 참  a| 
컴포넌트의 이름을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentMinVersion | 문자열 | 거짓  a| 
해당 구성 요소에 필요한 최소 버전을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.




| componentMaxVersion | 문자열 | 거짓  a| 
해당 구성 요소에 필요한 최대 버전을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
package_1.0_get_response_body

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-package"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| packageName | 문자열 | 참  a| 
패키지 이름이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 31 예시 값은 다음과 같습니다.
* "acc"
* "acs"
* "Trident"




| packageVersion | 문자열 | 참  a| 
패키지의 SemVer를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.




| packageType | 문자열 | 참  a| 
패키지 유형을 나타내는 JSON 문자열로, 전체 설치 패키지인지 패치인지 여부를 나타냅니다. 정의된 값은 다음과 같습니다.

* "설치"
* "패치"




| bundleName | 배열[string] | 거짓  a| 
패키지가 포함된 번들의 이름을 포함하는 JSON 문자열의 JSON 배열입니다.



| severityLevel | 문자열 | 참  a| 
이 패치 또는 설치의 심각도 수준을 설명하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "recommended" - 설치를 권장합니다 - 기본값
* "critical" - 중요한 버그 수정 및/또는 보안 패치를 해결하기 위해 설치를 강력히 권장합니다




| packageState | 문자열 | 참  a| 
패키지의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 패키지 검증 및 가져오기가 완료되면 상태는 "complete"로 표시됩니다. 그렇지 않으면 상태는 "incomplete"로 표시됩니다. 정의된 값은 다음과 같습니다.

* "verifying" - 패키지가 유효성 검사를 받고 있습니다.
* "corrupt" - 패키지가 손상되었습니다.
* "incomplete" - 패키지에 일부 요소가 누락되었습니다.
* "available" - 패키지와 관련된 모든 요소가 사용 가능하며 패키지를 바로 사용할 수 있습니다.




| packageStateTransitions | 배열[link:#type_astra_stateTransition["type_astra_stateTransition"]] | 참  a| 
JSON 객체의 JSON 배열로, 각 객체는 지정된 상태에서 허용되는 상태 전환 집합을 나타냅니다. 각 JSON 객체에는 "from" 및 "to" 필드가 포함되어 있으며, "from" 값은 상태 이름이고 "to" 값은 허용되는 대상 상태의 배열입니다. 정의된 값은 다음과 같습니다.

* 상태 전이 스키마를 준수합니다.




| packageStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
현재 "상태"에 대한 추가 세부 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| 이미지 | 배열[link:#images["이미지"]] | 거짓  a| 
패키지의 일부인 Docker 이미지를 각각 포함하는 JSON 객체의 JSON 배열입니다.



| 아티팩트 | 배열[link:#artifacts["아티팩트"]] | 거짓  a| 
이 패키지와 관련된 추가 아티팩트(바이너리 및 기타)를 설명하는 JSON 객체의 JSON 배열입니다.



| 파일 | 배열[link:#files["파일"]] | 거짓  a| 
이 패키지와 관련된 이미지 이외의 아티팩트를 각각 나타내는 JSON 객체의 JSON 배열입니다.



| upgradableVersions | link:#upgradableVersions["upgradableVersions"] | 거짓  a| 
패키지 버전으로 업그레이드할 수 있는 최소 및 최대 버전을 포함하는 JSON 객체입니다.



| 종속성 | 배열[link:#dependencies["종속성"]] | 거짓  a| 
이 패키지를 설치하는 데 필요한 특정 종속성의 최소 버전을 설명하는 JSON 객체의 JSON 배열



| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다.


|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_목록

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 계속 | 문자열 | 거짓  a| 



| 카운트 | 숫자 | 거짓  a| 



| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====