---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-credentials.html 
summary: 모든 자격 증명 나열 
---
= 모든 자격 증명 나열
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

컬렉션에서 일치하는 모든 리소스를 JSON 배열로 반환합니다. 요청에 개별 필드가 지정된 경우, items JSON 배열에는 지정된 순서대로 각 일치하는 리소스에 대해 요청된 필드가 포함됩니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| 계속 |  | 쿼리 | 거짓  a| 
목록 표시를 재개할 토큰을 나타냅니다.

URL 예시: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI 예시: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| 필터 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 리소스를 반환하기 위해 어떤 필드를 일치시켜야 하는지를 나타냅니다.

지원되는 연산자는 다음과 같습니다.

* eq - 같음
* lt/gt - 미만/초과
* lte/gte - 이하/이상


URL 예: "filter=field%20eq%20%27value%27"

OpenAPI 예: "field eq 'value'"



| 포함 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 어떤 필드를 반환해야 하는지 지정합니다.

URL 예: "include=id", "include=id,name"

OpenAPI 예: "id"

* 예: id,name




| 제한 | 문자열 | 쿼리 | 거짓  a| 
컬렉션 목록을 표시할 때 반환할 최대 리소스 수를 나타냅니다.

URL 예: "limit=2"

OpenAPI 예제: "2"



| 주문 | 문자열 | 쿼리 | 거짓  a| 
컬렉션을 나열할 때 리소스의 정렬 순서를 나타냅니다.

URL 예시: "orderBy=name", "orderBy=name%20desc"

OpenAPI 예: "name desc"

|===


== 응답

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 항목 | array[다음 중 하나: link:#credential_1_1_get_response_body["credential_1.1_get_response_body"], array[]] | 참  a| 



| 메타데이터 | link:#type_astra_metadata_list["type_astra_메타데이터_목록"] | 참  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credentials",
  "version": "1.1",
  "items": [
    [
      "f97f3441-075e-4f9b-9d1e-47f9f62a3fc4",
      "myCert"
    ],
    [
      "5e365b4d-034f-4f13-95ef-d3a7fbc0df3d",
      "kubeconfig"
    ],
    [
      "11ceb350-1999-4b79-80a6-46a980a27856",
      "password"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
credential_1.1_get_response_body

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-credential"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
사용자가 지정한 이름을 포함하는 JSON 문자열입니다. 사용자 자격 증명이 생성될 때 이름은 해당 사용자의 UUID로 설정됩니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| keyType | 문자열 | 거짓  a| 
keyStore의 콘텐츠에 대한 선택적 사용자 지정 데이터 유효성 검사 유형 설명자를 포함하는 JSON 문자열입니다. 확장된 업데이트 제약 조건:

* 리소스에 keyType이 존재하지 않고 업데이트에서도 지정되지 않은 경우, 해당 keyType은 업데이트된 리소스에 계속 존재해서는 안 됩니다.
* 리소스에 keyType이 존재하지 않지만 업데이트에서 지정된 경우, 해당 keyType을 리소스에 추가하고 유효성 검사를 수행해야 합니다. 유효성 검사에 실패하면 업데이트가 실패합니다.
* 리소스에 keyType이 존재하지만 업데이트에서 지정되지 않은 경우, 해당 keyType을 유지해야 합니다.
* 리소스에 keyType이 존재하고 업데이트에서 지정되었으며 지정된 keyType이 기존 keyType과 일치하는 경우 해당 keyType을 유지해야 합니다.
* 리소스에 keyType이 존재하고 업데이트에 지정되었으며, 지정된 keyType이 기존 keyType과 다른 경우 업데이트가 실패합니다. 정의된 값은 다음과 같습니다.
* "generic" - 자격 증명은 일반적인 데이터 모음입니다. 이는 keyType을 포함하지 않는 것과 같습니다.
* 확장 검증은 다음과 같이 수행됩니다.
* keyStore에 하나 이상의 문자열이 있어야 합니다.
* keyStore의 모든 문자열은 base64로 인코딩된 값을 가져야 합니다.
* "passwordHash" - 자격 증명은 비밀번호 해시입니다.
* 확장 검증은 다음과 같이 수행됩니다.
* 자격 증명의 이름은 고유해야 합니다.
* 자격 증명의 이름은 유효한 사용자 리소스 ID와 동일해야 합니다.
* 자격 증명의 이름은 변경해서는 안 됩니다.
* 해당 사용자 리소스는 "authProvider"가 "local"이어야 합니다.
* base64로 인코딩된 평문 암호를 포함하는 값을 가진 "평문" 문자열이 keyStore 내에 존재해야 합니다.
* 비밀번호 평문은 계정의 비밀번호 정책을 준수해야 합니다.
* 비밀번호는 해시값으로 저장됩니다.
* "change" 문자열은 keyStore 내에 base64로 인코딩된 "true" 또는 "false" 문자열 값을 포함하여 존재해야 합니다.
* passwordHash 유형의 자격 증명은 이름으로 표시된 사용자 ID가 존재하지 않는 경우에만 삭제할 수 있습니다.
* "apikey" - 자격 증명은 API 키입니다.
* 확장 검증은 다음과 같이 수행됩니다.
* keyStore 내에 base64로 인코딩된 임의의 문자열을 포함하는 값을 가진 "apikey" 문자열이 존재해야 합니다.
* "kubeconfig" - 자격 증명은 kubeconfig입니다.
* 확장 검증은 다음과 같이 수행됩니다.
* keyStore 내에 base64로 인코딩된 JSON kubeconfig 파일을 포함하는 값을 가진 "base64" 문자열이 존재해야 합니다.
* kubeconfig 파일에는 단일 클러스터에 대한 설명만 포함되어야 합니다.
* keyStore 내에 다른 필드가 존재할 수 없습니다.
* "certificate" - 자격 증명은 PEM 인코딩 인증서입니다
* 확장 검증은 다음과 같이 수행됩니다.
* keyStore 내에 base64로 인코딩된 PEM 인증서를 포함하는 값을 가진 "certificate" 문자열이 존재해야 합니다.
* "privkey" - 자격 증명은 PEM 형식으로 인코딩된 개인 키입니다.
* 확장 검증은 다음과 같이 수행됩니다.
* keyStore 내에 base64로 인코딩된 PEM 개인 키를 포함하는 값을 가진 "privkey" 문자열이 존재해야 합니다.
* "s3" - 해당 자격 증명이 Simple Storage Service(S3) 액세스용임을 나타냅니다.
* 확장 검증은 다음과 같이 수행됩니다.
* "accessKey" 문자열은 base64로 인코딩된 S3 액세스 키를 포함하는 값과 함께 keyStore 내에 존재해야 합니다.
* "accessSecret" 문자열은 base64로 인코딩된 S3 액세스 비밀 키를 포함하는 값과 함께 keyStore 내에 존재해야 합니다.




| 유효합니다 | 문자열 | 참  a| 
자격 증명의 사용 유효성을 설명하는 JSON 문자열입니다. 생략 시 기본값은 "true"입니다. 정의된 값은 다음과 같습니다.

* "true" - 해당 자격 증명을 사용할 수 있습니다.
* "false" - 해당 자격 증명은 사용해서는 안 됩니다.




| validFromTimestamp | 문자열 | 거짓  a| 
자격 증명이 유효한 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 이는 자격 증명 순환에 사용됩니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| validUntilTimestamp | 문자열 | 거짓  a| 
자격 증명이 더 이상 유효하지 않은 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 이는 자격 증명 순환에 사용됩니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_목록

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 계속 | 문자열 | 거짓  a| 



| 카운트 | 숫자 | 거짓  a| 



| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====