---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appbackups-appassets-.html 
summary: 앱의 애플리케이션 백업에서 애플리케이션 자산을 검색합니다. 
---
= 앱의 애플리케이션 백업에서 애플리케이션 자산을 검색합니다.
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups/{appBackup_id}/appAssets/{appAsset_id}`#

JSON 응답 본문에 저장된 애플리케이션 자산 API 리소스를 반환합니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| app_id | 문자열 | 경로 | 참  a| 
포함하는 앱 리소스의 ID



| appBackup_id | 문자열 | 경로 | 참  a| 
포함된 appBackup 리소스의 ID



| appAsset_id | 문자열 | 경로 | 참  a| 
목록에 표시할 appAsset 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored Application Asset API resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-appAsset"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| assetType | 문자열 | 참  a| 
Kubernetes에서 가져온 자산의 유형을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 
Kubernetes 메타데이터가 생성된 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| GVK | link:#GVK["GVK"] | 참  a| 
Kubernetes 그룹/버전/종류를 포함하는 JSON 객체입니다.



| 리소스 | link:#type_json["type_json"] | 거짓  a| 
Kubernetes 리소스 정의의 전체 내용을 포함하는 JSON 객체입니다.



| assetID | 문자열 | 참  a| 
Kubernetes에서 할당한 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 라벨 | 배열[link:#labels["라벨"]] | 참  a| 
자산과 연결된 Kubernetes 레이블을 각각 포함하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| assetName | 문자열 | 참  a| 
Kubernetes에서 할당한 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 네임스페이스 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 네임스페이스를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 메타데이터 | link:#type_astra_metadata["type_astra_메타데이터"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAsset",
  "version": "1.1",
  "id": "6415e851-b820-553b-9432-ebd057d1917d",
  "assetType": "Pod",
  "creationTimestamp": "2020-08-06T12:24:52.256624Z",
  "GVK": {
    "group": "apps",
    "kind": "Pod",
    "version": "v1"
  },
  "assetID": "93ec0c61-d993-4aa1-bb08-f4dcdd5e97f6",
  "labels": [
    {
      "name": "app",
      "value": "mediawiki"
    },
    {
      "name": "pod-template-hash",
      "value": "69c6fcf864"
    }
  ],
  "assetName": "mediawiki-69c6fcf864-2wx6l",
  "namespace": "wiki",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Kubernetes 그룹/버전/종류를 포함하는 JSON 객체입니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 그룹 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 그룹 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 종류 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 kind 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254




| 버전 | 문자열 | 거짓  a| 
Kubernetes에서 할당한 버전 식별자가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 254


|===
[role="api-collapsible-fifth-title"]
type_json

Kubernetes 리소스 정의의 전체 내용을 포함하는 JSON 객체입니다.

[role="api-collapsible-fifth-title"]
라벨

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
레이블 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| 값 | 문자열 | 참  a| 
레이블 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 참  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 참  a| 



| modificationTimestamp | 문자열 | 참  a| 



| 생성 시 | 문자열 | 참  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====