---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-upgrades-.html 
summary: 업그레이드 검색 
---
= 업그레이드 검색
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

JSON 응답 본문에 저장된 업그레이드 API 리소스를 반환합니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| upgrade_id | 문자열 | 경로 | 참  a| 
나열할 업그레이드 컬렉션의 ID

|===


== 응답

[source]
----
Status: 200, Returns the stored Upgrade API resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-upgrade"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| componentName | 문자열 | 참  a| 
업그레이드할 수 있는 소프트웨어 유형의 이름이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | 문자열 | 참  a| 
업그레이드 가능한 구성 요소의 URI가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 3
* 최대 길이: 4095




| componentID | 문자열 | 참  a| 
업그레이드할 수 있는 구성 요소의 전역적으로 고유한 식별자를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| upgradeVersion | 문자열 | 참  a| 
SemVer로 업그레이드할 수 있는 소프트웨어 이미지 파일의 SemVer를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.




| currentVersion | 문자열 | 참  a| 
업그레이드할 엔티티의 현재 SemVer를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* SemVer 스키마를 준수합니다.




| 종속성 | 배열[string] | 참  a| 
JSON 문자열 배열입니다. 각 문자열에는 이 업그레이드를 진행하기 전에 완료해야 하는 업그레이드의 UUID가 포함되어 있습니다. 어떤 업그레이드를 필수 조건으로 수행할지, 그리고 어떤 순서로 수행할지를 결정하는 데 사용됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 상태 | 문자열 | 참  a| 
업그레이드의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 자동 업그레이드가 활성화된 경우 업그레이드는 "scheduled" 상태로 시작됩니다. 그렇지 않으면 업그레이드는 "proposed" 상태로 시작됩니다. 정의된 값은 다음과 같습니다.

* "unavailable" - 현재 업그레이드를 이용할 수 없습니다.
* "proposed" - 업그레이드가 제안되었지만 승인될 때까지 자동으로 실행되지 않습니다.
* "scheduled" - 업그레이드가 승인되었지만 종속성, 시간 제약 또는 사용 가능한 리소스로 인해 아직 설치할 준비가 되지 않았습니다.
* "running" - 업그레이드가 진행 중입니다.
* "complete" - 업그레이드가 완료되었습니다.
* "failed" - 업그레이드가 완료되지 않았습니다.




| stateDesired | 문자열 | 참  a| 
"state"에 대해 원하는 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 이 필드는 사용자가 리소스의 상태 변경을 직접 요청할 수 있는 경우에만 포함됩니다. 정의된 값은 다음과 같습니다.

* "proposed" - 업그레이드가 승인되지 않았으며 수행해서는 안 됩니다
* "scheduled" - 업그레이드가 승인되었으며 지정된 기간 내에 수행되어야 합니다.
* "running" - 업그레이드는 시간 창과 관계없이 즉시 수행되어야 합니다




| stateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
현재 "상태"에 대한 추가 세부 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp 및 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "id": "aa9a8e88-c012-55b1-b514-7cd94dc79008",
  "componentName": "trident",
  "componentInstance": "https://<dns_name>/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/fdda3ff3-a46a-43a4-902e-444fde2baeba/storageBackends/72d19c3c-eb43-4bec-b23e-a228c900aded",
  "componentID": "72d19c3c-eb43-4bec-b23e-a228c900aded",
  "upgradeVersion": "21.07.1",
  "currentVersion": "21.04.1",
  "dependencies": [],
  "state": "scheduled",
  "stateDesired": "scheduled",
  "stateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidParams | 배열[link:#invalidParams["invalidParams"]] | 거짓  a| 
유효하지 않은 쿼리 매개변수 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp 및 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
====