---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v1-apps-executionhooks.html 
summary: 앱에 대한 새 실행 후크 생성 
---
= 앱에 대한 새 실행 후크 생성
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks`#

생성할 Execution Hook API 리소스에 대한 원하는 값을 나타냅니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| app_id | 문자열 | 경로 | 참  a| 
포함하는 앱 리소스의 ID

|===


== 요청 본문

생성할 Execution Hook API 리소스에 대한 원하는 값을 나타냅니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-executionHook"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| 이름 | 문자열 | 참  a| 
사용자가 지정한 리소스 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63 이름은 모든 실행 후크 리소스에서 고유해야 합니다.




| hookType | 문자열 | 참  a| 
훅 유형을 정의하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "netapp" - NetApp에서 제공하는 실행 후크입니다.
* "custom" - 특정 앱 ID와 연결됩니다. hookType "netapp"인 실행 후크 리소스는 읽기 전용입니다.




| matchingCriteria | 배열[link:#matchingCriteria["matchingCriteria"]] | 거짓  a| 
실행 후크에 대한 일치 기준을 설명하는 JSON 객체의 JSON 배열입니다. 여러 개의 matchingCriteria가 지정된 경우 기준에 논리적 AND가 적용됩니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0
* 최대 항목 수: 10




| 작업 | 문자열 | 참  a| 
일치 기준이 충족될 경우 실행 후크가 실행할 작업을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "스냅샷"
* "백업"
* "복원"
* "페일오버"




| 단계 | 문자열 | 참  a| 
훅이 실행될 액션의 단계를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pre" - 실행 후크는 지정된 작업 전에 실행됩니다.
* "post" - 지정된 작업 후에 실행 후크가 실행됩니다. "snapshot" 작업의 값은 "pre"와 "post"입니다. "backup" 작업의 값은 "pre"와 "post"입니다. "restore" 작업의 값은 "post"입니다. "failover" 작업의 값은 "post"입니다.




| hookSourceID | 문자열 | 참  a| 
이 실행 후크를 통해 실행되는 후크 소스 ID가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 인수 | 배열[string] | 거짓  a| 
소스에 대한 인수의 JSON 문자열로 구성된 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0
* 최대 항목 수: 16
* 최소 길이: 0
* 최대 길이: 127




| appID | 문자열 | 참  a| 
이 후크가 연결된 애플리케이션의 관련 ID가 포함된 JSON 문자열입니다. 즉, 설정된 경우 다른 일치 기준이 포함됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 활성화됨 | 문자열 | 거짓  a| 
실행 후크가 활성화되었는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 실행 후크가 활성화되어 지정된 대로 실행됩니다.
* "false" - 실행 후크가 비활성화되어 실행되지 않습니다. 기본값은 "true"입니다.




| 설명 | 문자열 | 거짓  a| 
후크 소스에 대한 사용자 지정 설명을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 0
* 최대 길이: 511




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 거짓  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.요청 예시
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "name": "Payroll",
  "hookType": "custom",
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook"
}
----
====


== 응답

[source]
----
Status: 201, Returns the newly created executionHook resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-executionHook"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
사용자가 지정한 리소스 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63 이름은 모든 실행 후크 리소스에서 고유해야 합니다.




| hookType | 문자열 | 참  a| 
훅 유형을 정의하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "netapp" - NetApp에서 제공하는 실행 후크입니다.
* "custom" - 특정 앱 ID와 연결됩니다. hookType "netapp"인 실행 후크 리소스는 읽기 전용입니다.




| matchingCriteria | 배열[link:#matchingCriteria["matchingCriteria"]] | 참  a| 
실행 후크에 대한 일치 기준을 설명하는 JSON 객체의 JSON 배열입니다. 여러 개의 matchingCriteria가 지정된 경우 기준에 논리적 AND가 적용됩니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0
* 최대 항목 수: 10




| matchingContainers | 배열[link:#matchingContainers["matchingContainers"]] | 거짓  a| 
정의된 앱 내에서 구성된 일치 기준과 일치하는 각 컨테이너의 JSON 객체로 구성된 JSON 배열입니다.



| matchingImages | 배열[string] | 거짓  a| 
일치하는 컨테이너 이미지에 대한 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0
* 최대 항목 수: 4095
* 최소 길이: 1
* 최대 길이: 255




| 작업 | 문자열 | 참  a| 
일치 기준이 충족될 경우 실행 후크가 실행할 작업을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "스냅샷"
* "백업"
* "복원"
* "페일오버"




| 단계 | 문자열 | 참  a| 
훅이 실행될 액션의 단계를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pre" - 실행 후크는 지정된 작업 전에 실행됩니다.
* "post" - 지정된 작업 후에 실행 후크가 실행됩니다. "snapshot" 작업의 값은 "pre"와 "post"입니다. "backup" 작업의 값은 "pre"와 "post"입니다. "restore" 작업의 값은 "post"입니다. "failover" 작업의 값은 "post"입니다.




| hookSourceID | 문자열 | 참  a| 
이 실행 후크를 통해 실행되는 후크 소스 ID가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 인수 | 배열[string] | 거짓  a| 
소스에 대한 인수의 JSON 문자열로 구성된 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 항목: 0
* 최대 항목 수: 16
* 최소 길이: 0
* 최대 길이: 127




| appID | 문자열 | 거짓  a| 
이 후크가 연결된 애플리케이션의 관련 ID가 포함된 JSON 문자열입니다. 즉, 설정된 경우 다른 일치 기준이 포함됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 활성화됨 | 문자열 | 참  a| 
실행 후크가 활성화되었는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 실행 후크가 활성화되어 지정된 대로 실행됩니다.
* "false" - 실행 후크가 비활성화되어 실행되지 않습니다. 기본값은 "true"입니다.




| 설명 | 문자열 | 거짓  a| 
후크 소스에 대한 사용자 지정 설명을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 0
* 최대 길이: 511




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "id": "5f7e2e31-280d-5984-a28b-2d19ab5b77c0",
  "name": "Payroll",
  "hookType": "custom",
  "matchingCriteria": [],
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidFields | 배열[link:#invalidFields["invalidFields"]] | 거짓  a| 
유효하지 않은 요청 본문 필드 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 거짓  a| 
일치 기준 유형을 식별하는 JSON 문자열입니다.



| 값 | 문자열 | 거짓  a| 
지정된 일치 유형에 대한 정규 표현식을 포함하는 JSON 문자열입니다. 정규 표현식 구문: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
일치 기준 유형을 식별하는 JSON 문자열입니다.



| 값 | 문자열 | 참  a| 
지정된 일치 유형에 대한 정규 표현식을 포함하는 JSON 문자열입니다. 정규 표현식 구문: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
type_k8s_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
matchingContainers

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| podName | 문자열 | 거짓  a| 
일치하는 컨테이너의 Pod 이름의 JSON 문자열입니다.



| podLabels | 배열[link:#type_k8s_label["type_k8s_label"]] | 거짓  a| 
일치하는 컨테이너의 파드 레이블을 담은 레이블 객체의 JSON 배열입니다.



| containerImage | 문자열 | 거짓  a| 
일치하는 컨테이너 이미지의 JSON 문자열입니다.



| containerName | 문자열 | 거짓  a| 
일치하는 컨테이너 이름의 JSON 문자열입니다.



| namespaceName | 문자열 | 거짓  a| 
일치하는 컨테이너의 Pod 네임스페이스 이름의 JSON 문자열입니다.

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
유효하지 않은 요청 본문 필드의 이름



| 이유 | 문자열 | 참  a| 
요청 본문 필드가 유효하지 않은 이유

|===
====