---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-topology-v1-storagebackends.html 
summary: 새 스토리지 백엔드 생성 
---
= 새 스토리지 백엔드 생성
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends`#

생성할 스토리지 백엔드 API 리소스에 대한 원하는 값을 나타냅니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}


|===


== 요청 본문

생성할 스토리지 백엔드 API 리소스에 대한 원하는 값을 나타냅니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-storageBackend"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| backendName | 문자열 | 거짓  a| 
사용자가 지정한 스토리지 백엔드 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| backendType | 문자열 | 참  a| 
표현되는 스토리지 백엔드의 유형을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "ontap" - 스토리지 백엔드는 NetApp ONTAP 시스템을 나타냅니다
* 열거형: ["ONTAP"]
* 예: ONTAP




| backendVersion | 문자열 | 거짓  a| 
스토리지 백엔드의 버전을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| backendCredentialsName | 문자열 | 거짓  a| 
스토리지 백엔드에 사용되는 하나 이상의 자격 증명 리소스 이름을 나타내는 값을 포함하는 JSON 문자열입니다. 여러 자격 증명 객체가 동일한 이름을 가질 때 자격 증명 순환이 가능합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 거짓  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.요청 예시
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageBackend",
  "version": "1.3",
  "backendName": "st1-45",
  "backendType": "ontap",
  "backendCredentialsName": "st1-45-cred"
}
----
====


== 응답

[source]
----
Status: 201, Returns the newly created storageBackend resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-storageBackend"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| backendName | 문자열 | 참  a| 
사용자가 지정한 스토리지 백엔드 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| backendType | 문자열 | 참  a| 
표현되는 스토리지 백엔드의 유형을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "ontap" - 스토리지 백엔드는 NetApp ONTAP 시스템을 나타냅니다
* 열거형: ["ONTAP"]
* 예: ONTAP




| backendVersion | 문자열 | 참  a| 
스토리지 백엔드의 버전을 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| backendCredentialsName | 문자열 | 참  a| 
스토리지 백엔드에 사용되는 하나 이상의 자격 증명 리소스 이름을 나타내는 값을 포함하는 JSON 문자열입니다. 여러 자격 증명 객체가 동일한 이름을 가질 때 자격 증명 순환이 가능합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| configVersion | 문자열 | 거짓  a| 
스토리지 백엔드에서 사용할 활성 구성을 나타내는 값이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| 상태 | 문자열 | 참  a| 
스토리지 백엔드의 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "discovered" - 관리형 클러스터에서 스토리지 백엔드가 검색되었습니다.
* "running" - 스토리지 백엔드가 정상적으로 실행 중입니다.
* "unknown" - 스토리지 백엔드의 상태를 확인할 수 없습니다
* "failed" - 스토리지 백엔드를 사용할 수 없는 상태입니다




| stateDesired | 문자열 | 거짓  a| 
스토리지 백엔드의 원하는 작동 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "running" - 스토리지 백엔드가 정상 실행 상태입니다




| stateUnready | 배열[string] | 참  a| 
JSON 문자열의 JSON 배열로, 각 문자열은 스토리지 백엔드가 "running" 상태로 전환할 수 없는 이유, "failed" 또는 "unknown" 상태로 전환된 이유 및/또는 "failed" 상태로 전환될 위험이 있는 이유를 나타냅니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| managedState | 문자열 | 참  a| 
스토리지 백엔드의 관리 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "pending" - 스토리지 백엔드가 검색되거나 추가될 예정입니다
* "unmanaged" - 스토리지 백엔드가 "discovered" 상태이며, 관리되지 않고 있으며, 관리 대상이 될 수 있습니다
* "managed" - 스토리지 백엔드가 "running" 또는 "unknown" 상태이며 관리되고 있습니다




| managedStateUnready | 배열[string] | 참  a| 
스토리지 백엔드를 관리할 수 없는 이유를 각각 나타내는 JSON 문자열의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| healthState | 문자열 | 거짓  a| 
스토리지 백엔드의 상태를 나타내는 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "indeterminate" - 리소스의 상태를 확인할 수 없습니다(예: 연결 부족으로 인해)
* "normal" - 해당 리소스에는 알려진 문제가 없으며 인터페이스 사양에 따라 서비스를 제공할 수 있습니다.
* "warning" - 해당 리소스에는 인터페이스 사양에 따라 서비스를 제공하는 데 지장을 주지 않는 알려진 문제가 있습니다.
* "critical" - 해당 리소스에는 인터페이스 사양에 따라 서비스를 제공하는 것을 방해하는 알려진 문제가 있습니다.




| healthStateUnready | 배열[string] | 거짓  a| 
JSON 문자열의 JSON 배열로, 각 문자열은 스토리지 백엔드가 정상 상태가 아닌 이유를 나타냅니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| protectionState | 문자열 | 참  a| 
스토리지 백엔드의 보호 상태를 나타내는 값을 포함하는 JSON 문자열입니다. ONTAP의 경우 "unknown"입니다. 정의된 값은 다음과 같습니다.

* "protected" - 스토리지 백엔드에 보호 정책이 정의되어 있으며 해당 정책을 준수하고 있습니다.
* "partial" - 스토리지 백엔드에 보호 정책이 정의되어 있지만 해당 정책을 준수하지 않고 있습니다.
* "none" - 스토리지 백엔드가 보호되지 않습니다.
* "unknown" - 스토리지 백엔드 보호 정책 준수 여부를 확인할 수 없습니다.
* enum: ["protected", "partial", "none", "unknown"]
* 예: protected




| protectionStateUnready | 배열[string] | 참  a| 
보호 정책이 규정을 준수하지 않는 이유를 각각 나타내는 JSON 문자열들의 JSON 배열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 127




| 기능 | link:#capabilities["기능"] | 참  a| 
이 스토리지 백엔드 기능을 포함하는 JSON 객체입니다.



| ONTAP | link:#ontap["ONTAP"] | 거짓  a| 
ONTAP 클러스터와 관련된 특정 정보를 포함하는 JSON 객체입니다.

* additionalProperties: false




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageBackend",
  "version": "1.3",
  "id": "04ad4237-3c89-5ca5-8a40-282ab5eb6428",
  "backendName": "st1-45",
  "backendType": "ontap",
  "backendVersion": "9.8",
  "backendCredentialsName": "st1-45-cred",
  "state": "running",
  "stateUnready": [],
  "managedState": "managed",
  "managedStateUnready": [],
  "protectionState": "unknown",
  "protectionStateUnready": [
    "Waiting for storage backend discovery"
  ],
  "ontap": {
    "authenticationStyle": "basic",
    "backendManagementIP": "10.193.179.105",
    "managementIPs": [
      "10.193.188.110",
      "10.193.179.105",
      "10.193.179.106"
    ]
  },
  "capabilities": {
    "flexClone": "true",
    "snapMirror": "true",
    "s3": "true"
  },
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidFields | 배열[link:#invalidFields["invalidFields"]] | 거짓  a| 
유효하지 않은 요청 본문 필드 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidFields | 배열[link:#invalidFields["invalidFields"]] | 거짓  a| 
유효하지 않은 요청 본문 필드 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
기능

이 스토리지 백엔드 기능을 포함하는 JSON 객체입니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| flexClone | 문자열 | 참  a| 
이 스토리지 백엔드가 FlexClone을 지원하는지 여부를 나타내는 JSON 문자열입니다.



| snapMirror | 문자열 | 참  a| 
이 스토리지 백엔드가 SnapMirror를 지원하는지 나타내는 JSON 문자열입니다.



| s3 | 문자열 | 참  a| 
이 스토리지 백엔드가 s3를 지원하는지 여부를 나타내는 JSON 문자열입니다.

|===
[role="api-collapsible-fifth-title"]
ONTAP

ONTAP 클러스터와 관련된 특정 정보를 포함하는 JSON 객체입니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| authenticationStyle | 문자열 | 참  a| 
ONTAP 인증이 사용자 이름/암호 조합을 사용하는지 또는 인증서를 사용하는지를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "basic" - 사용자 이름/비밀번호를 사용합니다.
* "certificate" - 인증서를 사용합니다
* enum: ["basic", "certificate"]
* 예: 기본




| 백엔드 관리 IP | 문자열 | 거짓  a| 
이 ONTAP 클러스터에 연결하는 데 사용된 IP 주소가 포함된 JSON 문자열입니다.



| managementIP | 배열[string] | 거짓  a| 
이 ONTAP 클러스터에 연결하는 데 사용되는 모든 가능한 관리 IP 목록이 포함된 JSON 문자열의 JSON 배열입니다. 이는 Trident를 통해 감지된 백엔드와 Astra의 스토리지 백엔드를 상호 연관시키는 데 사용됩니다.

* uniqueItems: 1


|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
유효하지 않은 요청 본문 필드의 이름



| 이유 | 문자열 | 참  a| 
요청 본문 필드가 유효하지 않은 이유

|===
====