---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-certificates.html 
summary: 새 인증서 생성 
---
= 새 인증서 생성
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/certificates`#

생성할 Certificate API 리소스에 대한 원하는 값을 나타냅니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}


|===


== 요청 본문

생성할 Certificate API 리소스에 대한 원하는 값을 나타냅니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-certificate"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| certUse | 문자열 | 거짓  a| 
인증서 사용 용도를 나타내는 JSON 문자열입니다. 지정하지 않으면 기본값으로 "rootCA"가 사용됩니다. 정의된 값은 다음과 같습니다.

* "rootCA" - 인증서는 해당 CA가 서명한 모든 인증서를 신뢰하는 데 사용되는 CA(인증 기관) 인증서입니다.
* "intermediateCA" - 인증서는 루트 CA에서 발급한 중간 CA 인증서입니다.




| 인증서 | 문자열 | 참  a| 
base64로 인코딩된 PKCS-11 형식 인증서(PEM)를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* base64 인코딩 데이터 스키마를 준수합니다




| isSelfSigned | 문자열 | 거짓  a| 
인증서가 자체 서명되었는지 여부를 나타내는 JSON 문자열입니다. 생성 시 제공되지 않으면 기본값은 "false"입니다. 업데이트 시:

* 값이 제공되면 해당 값이 사용됩니다.
* 값이 제공되지 않고 업데이트에 "cert" 필드가 포함된 경우 해당 값은 "false"로 설정됩니다.
* 값이 제공되지 않고 업데이트에 "cert" 필드가 포함되지 않은 경우 기존 값이 유지됩니다. 정의된 값은 다음과 같습니다.
* "true" - 해당 인증서는 자체 서명되었습니다.
* "false" - 해당 인증서는 자체 서명된 것이 아닙니다.




| trustStateDesired | 문자열 | 거짓  a| 
인증서의 신뢰 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 생성 시 지정하지 않으면 기본값은 "trusted"입니다. 정의된 값은 다음과 같습니다.

* "untrusted" - 인증서를 신뢰할 수 없습니다.
* "trusted" - 인증서가 신뢰할 수 있는 것으로 표시됩니다.




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 거짓  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.요청 예시
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-certificate",
  "version": "1.1",
  "certUse": "rootCA",
  "cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZyVENDQTVXZ0F3MVJHbnFGbUJSSWRyV1kwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
}
----
====


== 응답

[source]
----
Status: 201, Returns the newly created certificate resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-certificate"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| certUse | 문자열 | 참  a| 
인증서 사용 용도를 나타내는 JSON 문자열입니다. 지정하지 않으면 기본값으로 "rootCA"가 사용됩니다. 정의된 값은 다음과 같습니다.

* "rootCA" - 인증서는 해당 CA가 서명한 모든 인증서를 신뢰하는 데 사용되는 CA(인증 기관) 인증서입니다.
* "intermediateCA" - 인증서는 루트 CA에서 발급한 중간 CA 인증서입니다.




| 인증서 | 문자열 | 참  a| 
base64로 인코딩된 PKCS-11 형식 인증서(PEM)를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* base64 인코딩 데이터 스키마를 준수합니다




| cn | 문자열 | 참  a| 
인증서에서 추출한 일반 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 511




| expiryTimestamp | 문자열 | 참  a| 
인증서 만료 시점을 나타내는 타임스탬프가 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* ISO-8601 날짜/시간 스키마를 준수합니다.




| isSelfSigned | 문자열 | 참  a| 
인증서가 자체 서명되었는지 여부를 나타내는 JSON 문자열입니다. 생성 시 제공되지 않으면 기본값은 "false"입니다. 업데이트 시:

* 값이 제공되면 해당 값이 사용됩니다.
* 값이 제공되지 않고 업데이트에 "cert" 필드가 포함된 경우 해당 값은 "false"로 설정됩니다.
* 값이 제공되지 않고 업데이트에 "cert" 필드가 포함되지 않은 경우 기존 값이 유지됩니다. 정의된 값은 다음과 같습니다.
* "true" - 해당 인증서는 자체 서명되었습니다.
* "false" - 해당 인증서는 자체 서명된 것이 아닙니다.




| trustState | 문자열 | 참  a| 
인증서의 신뢰도를 나타내는 열거형 값 중 하나를 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "untrusted" - 인증서를 신뢰할 수 없습니다.
* "trusted" - 인증서가 신뢰할 수 있는 것으로 표시됩니다.
* "expired" - 인증서가 만료되었으므로 신뢰할 수도 없고 신뢰할 수 없는 것도 아닙니다.




| trustStateTransitions | 배열[link:#type_astra_stateTransition["type_astra_stateTransition"]] | 참  a| 
JSON 객체의 JSON 배열로, 각 객체는 지정된 상태에서 허용되는 상태 전환 집합을 나타냅니다. 각 JSON 객체는 "from"과 "to" 필드를 포함하며, "from" 값은 상태의 이름이고 "to" 값은 허용되는 대상 상태의 배열입니다.



| trustStateDesired | 문자열 | 거짓  a| 
인증서의 신뢰 여부를 나타내는 값을 포함하는 JSON 문자열입니다. 생성 시 지정하지 않으면 기본값은 "trusted"입니다. 정의된 값은 다음과 같습니다.

* "untrusted" - 인증서를 신뢰할 수 없습니다.
* "trusted" - 인증서가 신뢰할 수 있는 것으로 표시됩니다.




| trustStateDetails | 배열[link:#type_astra_stateDetail["type_astra_stateDetail"]] | 참  a| 
인증서의 신뢰 상태에 대한 추가 정보를 나열하는 JSON 객체의 JSON 배열입니다. 정보가 없는 경우 이 배열은 비어 있습니다.

* 최소 항목: 0




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-certificate",
  "version": "1.1",
  "id": "a26cbed4-2183-58ce-aa19-e37ca8b0531a",
  "certUse": "rootCA",
  "cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZyVENDQTVXZ0F3MVJHbnFGbUJSSWRyV1kwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t",
  "cn": "vcenter.example.com",
  "isSelfSigned": "false",
  "expiryTimestamp": "2022-03-23T16:48:38.5233461Z",
  "trustState": "trusted",
  "trustStateTransitions": [
    {
      "from": "untrusted",
      "to": [
        "trusted"
      ]
    },
    {
      "from": "trusted",
      "to": [
        "untrusted"
      ]
    }
  ],
  "trustStateDesired": "trusted",
  "trustStateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidFields | 배열[link:#invalidFields["invalidFields"]] | 거짓  a| 
유효하지 않은 요청 본문 필드 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/7",
  "title": "Invalid JSON payload",
  "detail": "The request body is not valid JSON.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 응답

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== 응답

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== 오류

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 에서 | 문자열 | 참  a| 



| ~ | 배열[string] | 참  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
유효하지 않은 요청 본문 필드의 이름



| 이유 | 문자열 | 참  a| 
요청 본문 필드가 유효하지 않은 이유

|===
====