---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v1-apps-schedules.html 
summary: 앱에 대한 새 일정 생성 
---
= 앱에 대한 새 일정 생성
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules`#

생성할 Schedule API 리소스에 대해 원하는 값을 나타냅니다.



== 매개변수

[cols="5*"]
|===
| 이름 | 유형 | 에서 | 필수 요소입니다 | 설명 


| account_id | 문자열 | 경로 | 참  a| 
포함하는 계정 리소스의 ID

* 예: {{.Account}}




| app_id | 문자열 | 경로 | 참  a| 
포함하는 앱 리소스의 ID

|===


== 요청 본문

생성할 Schedule API 리소스에 대해 원하는 값을 나타냅니다.

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-schedule"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| 이름 | 문자열 | 참  a| 
일정의 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| 활성화됨 | 문자열 | 거짓  a| 
일정이 활성화되었는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 일정이 활성화되어 있습니다
* "false" - 일정이 활성화되어 있지 않습니다. 지정하지 않으면 기본값은 "true"입니다.




| 세분성 | 문자열 | 참  a| 
일정의 세분성을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "매시간"
* "일간"
* "주간"
* "월간"
* "사용자 정의"




| 분 | 문자열 | 거짓  a| 
일정을 실행할 분(0~59)을 나타내는 숫자 값이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-9]|[1-5][0-9]$"입니다. 이 필드는 세분성이 "hourly", "daily", "weekly" 또는 "monthly"로 설정된 경우에 존재합니다. 사용자 지정 일정의 경우 "0" 값이 반환됩니다.




| 시간 | 문자열 | 거짓  a| 
일정을 실행할 시간(0~23시)을 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-9]|[1][0-9]|[2][0-3]$"입니다. 이 필드는 세분성이 "daily", "weekly" 또는 "monthly"로 설정된 경우에 존재합니다.




| dayOfWeek | 문자열 | 거짓  a| 
일정을 실행할 요일(0-7)을 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-7]$"입니다. 이 필드는 granularity가 "weekly"로 설정된 경우에만 존재합니다.




| dayOfMonth | 문자열 | 거짓  a| 
일정을 실행할 날짜(1~31일)를 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[1-9]|[1-2][0-9]|[3][0-1]$"입니다. 이 필드는 세분성이 "monthly"로 설정된 경우에만 존재합니다.




| recurrenceRule | 문자열 | 거짓  a| 
RFC-5545 섹션 3.8.5.3을 포함하는 JSON 문자열입니다. 반복 규칙. DTSTART 매개변수의 경우 UTC 타임스탬프(접미사 "Z"로 표시)만 지원되며, 현재 시간 이전의 타임스탬프만 지원됩니다. RECUR 규칙 부분에서는 "FREQ"와 "INTERVAL"만 지원됩니다. FREQ 규칙 부분에서는 "MINUTELY"와 "HOURLY" 값만 지원됩니다. 이 필드는 세분성이 "custom"으로 설정된 경우에만 나타납니다.



| snapshotRetention | 문자열 | 참  a| 
보존할 스냅샷 개수를 나타내는 양수 값을 포함하는 JSON 문자열입니다. 0은 백업 후 스냅샷을 삭제해야 함을 의미합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다. "^(0|([1-9][0-9]*))$"




| backupRetention | 문자열 | 참  a| 
보관할 백업 개수를 나타내는 양수 값을 포함하는 JSON 문자열입니다. 0은 백업을 생성하지 않음을 의미합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다. "^(0|([1-9][0-9]*))$"




| bucketID | 문자열 | 거짓  a| 
백업 생성 시 저장할 버킷 ID를 지정하는 선택적 버킷 ID를 포함하는 JSON 문자열입니다. 지정하지 않으면 시스템에서 선택한 버킷이 사용됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 복제 | 문자열 | 거짓  a| 
각 스냅샷에 대해 AppMirror 복제를 트리거하는지 여부를 나타내는 JSON 문자열입니다. 애플리케이션에 AppMirror 관계가 정의된 경우에만 적용됩니다. 정의된 값은 다음과 같습니다.

* "true" - 해당 일정은 AppMirror 복제를 트리거합니다
* "false" - 일정이 AppMirror 복제를 트리거하지 않습니다. 지정하지 않으면 기본값은 "false"입니다.




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 거짓  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.요청 예시
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12"
}
----
====


== 응답

[source]
----
Status: 201, Returns the newly created schedule resource in the JSON response body.
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 
리소스의 미디어 유형입니다. 정의된 값은 다음과 같습니다.

* "application/astra-schedule"




| 버전 | 문자열 | 참  a| 
리소스 버전입니다. 정의된 값은 다음과 같습니다.

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| ID입니다 | 문자열 | 참  a| 
리소스의 전역 고유 식별자입니다. 정의된 값은 다음과 같습니다.

* UUIDv4 스키마를 준수합니다.




| 이름 | 문자열 | 참  a| 
일정의 이름을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63




| 활성화됨 | 문자열 | 참  a| 
일정이 활성화되었는지 여부를 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "true" - 일정이 활성화되어 있습니다
* "false" - 일정이 활성화되어 있지 않습니다. 지정하지 않으면 기본값은 "true"입니다.




| 세분성 | 문자열 | 참  a| 
일정의 세분성을 나타내는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* "매시간"
* "일간"
* "주간"
* "월간"
* "사용자 정의"




| 분 | 문자열 | 참  a| 
일정을 실행할 분(0~59)을 나타내는 숫자 값이 포함된 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-9]|[1-5][0-9]$"입니다. 이 필드는 세분성이 "hourly", "daily", "weekly" 또는 "monthly"로 설정된 경우에 존재합니다. 사용자 지정 일정의 경우 "0" 값이 반환됩니다.




| 시간 | 문자열 | 거짓  a| 
일정을 실행할 시간(0~23시)을 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-9]|[1][0-9]|[2][0-3]$"입니다. 이 필드는 세분성이 "daily", "weekly" 또는 "monthly"로 설정된 경우에 존재합니다.




| dayOfWeek | 문자열 | 거짓  a| 
일정을 실행할 요일(0-7)을 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[0-7]$"입니다. 이 필드는 granularity가 "weekly"로 설정된 경우에만 존재합니다.




| dayOfMonth | 문자열 | 거짓  a| 
일정을 실행할 날짜(1~31일)를 나타내는 숫자 값을 포함하는 JSON 문자열입니다. 정의된 값은 다음과 같습니다.

* 정의된 정규식은 "^[1-9]|[1-2][0-9]|[3][0-1]$"입니다. 이 필드는 세분성이 "monthly"로 설정된 경우에만 존재합니다.




| recurrenceRule | 문자열 | 거짓  a| 
RFC-5545 섹션 3.8.5.3을 포함하는 JSON 문자열입니다. 반복 규칙. DTSTART 매개변수의 경우 UTC 타임스탬프(접미사 "Z"로 표시)만 지원되며, 현재 시간 이전의 타임스탬프만 지원됩니다. RECUR 규칙 부분에서는 "FREQ"와 "INTERVAL"만 지원됩니다. FREQ 규칙 부분에서는 "MINUTELY"와 "HOURLY" 값만 지원됩니다. 이 필드는 세분성이 "custom"으로 설정된 경우에만 나타납니다.



| snapshotRetention | 문자열 | 참  a| 
보존할 스냅샷 개수를 나타내는 양수 값을 포함하는 JSON 문자열입니다. 0은 백업 후 스냅샷을 삭제해야 함을 의미합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다. "^(0|([1-9][0-9]*))$"




| backupRetention | 문자열 | 참  a| 
보관할 백업 개수를 나타내는 양수 값을 포함하는 JSON 문자열입니다. 0은 백업을 생성하지 않음을 의미합니다. 정의된 값은 다음과 같습니다.

* 최소 길이: 1
* 최대 길이: 63
* 정의된 정규 표현식은 다음과 같습니다. "^(0|([1-9][0-9]*))$"




| bucketID | 문자열 | 거짓  a| 
백업 생성 시 저장할 버킷 ID를 지정하는 선택적 버킷 ID를 포함하는 JSON 문자열입니다. 지정하지 않으면 시스템에서 선택한 버킷이 사용됩니다. 정의된 값은 다음과 같습니다.

* Astra 식별자 스키마를 준수합니다.




| 복제 | 문자열 | 거짓  a| 
각 스냅샷에 대해 AppMirror 복제를 트리거하는지 여부를 나타내는 JSON 문자열입니다. 애플리케이션에 AppMirror 관계가 정의된 경우에만 적용됩니다. 정의된 값은 다음과 같습니다.

* "true" - 해당 일정은 AppMirror 복제를 트리거합니다
* "false" - 일정이 AppMirror 복제를 트리거하지 않습니다. 지정하지 않으면 기본값은 "false"입니다.




| 메타데이터 | link:#type_astra_metadata_update["type_astra_메타데이터_업데이트"] | 참  a| 
리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "id": "49cbc480-5f7d-51e2-8f30-52b9a83a03b1",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 응답

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 응답

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 



| invalidFields | 배열[link:#invalidFields["invalidFields"]] | 거짓  a| 
유효하지 않은 요청 본문 필드 목록

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 응답

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 응답

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.응답 예
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 오류

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 유형 | 문자열 | 참  a| 



| 제목 | 문자열 | 참  a| 



| 세부 정보 | 문자열 | 참  a| 



| 상태 | 문자열 | 참  a| 



| correlationID | 문자열 | 거짓  a| 

|===
.예시 오류 응답
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 정의

.정의를 참조하세요
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 



| 값 | 문자열 | 참  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_메타데이터_업데이트

리소스와 연결된 클라이언트 및 서비스 지정 메타데이터입니다. 정의된 값은 다음과 같습니다.

* Astra 메타데이터 스키마를 준수합니다. 생성 시 지정하지 않으면 레이블이 없는 메타데이터 객체가 생성됩니다. 업데이트 시 지정하지 않으면 메타데이터 객체의 레이블인 creationTimestamp와 createdBy는 수정 없이 유지됩니다.


[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 라벨 | 배열[link:#type_astra_label["type_astra_label"]] | 거짓  a| 



| CreationTimestamp 를 클릭합니다 | 문자열 | 거짓  a| 



| modificationTimestamp | 문자열 | 거짓  a| 



| 생성 시 | 문자열 | 거짓  a| 



| modifiedBy | 문자열 | 거짓  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
잘못된 쿼리 매개변수의 이름



| 이유 | 문자열 | 참  a| 
쿼리 매개변수가 유효하지 않은 이유

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| 이름 | 유형 | 필수 요소입니다 | 설명 


| 이름 | 문자열 | 참  a| 
유효하지 않은 요청 본문 필드의 이름



| 이유 | 문자열 | 참  a| 
요청 본문 필드가 유효하지 않은 이유

|===
====